python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_001.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_002.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_003.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_004.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_005.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_006.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_007.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_008.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_009.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_010.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_011.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_012.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_013.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_014.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_015.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_016.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_017.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_018.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_019.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_020.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_021.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_022.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_023.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_024.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_025.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_026.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_027.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_028.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_029.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_030.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_031.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_032.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_033.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_034.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_035.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_036.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_037.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_038.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_039.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_040.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_041.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_042.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_043.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_044.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_045.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_046.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_047.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_048.py
##python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_052.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_058.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_059.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_060.py
##python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_061.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_064_2.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_064_3.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_066.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_067.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_068.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_069.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_070.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_071.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_072.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_073.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_074.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_075.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_076.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_077.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_078.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_079.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_080.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_081.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_SA/YW_ETFSS_SZSG_084.py


