python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_001.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_002.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_003.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_004.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_005.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_006.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_007.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_008.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_009.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_010.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_011.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_012.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_013.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_014.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_015.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_016.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_017.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_018.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_019.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_020.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_021.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_022.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_023.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_024.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_025.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_026.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_027.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_028.py
#python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_029.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_040.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_041.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_042.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_046_2.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_046_3.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_048.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_049.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_050.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_051.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_052.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_053.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_054.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_055.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_056.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_057.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_058.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_059.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_060.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_061.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_062.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_063.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_064.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_065.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_066.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_067.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_068.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_HA/YW_ETFSS_SHSH_069.py


