python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_001.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_002.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_003.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_004.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_005.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_006.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_007.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_008.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_009.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_010.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_011.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_012.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_013.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_014.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_015.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_016.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_017.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_018.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_019.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_020.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_021.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_022.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_023.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_024.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_025.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_026.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_027.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_028.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_029.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_030.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_031.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_032.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_033.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_034.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_035.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_036.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_037.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_038.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_039.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_040.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_041.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_042.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_043.py
