python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_001.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_002.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_003.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_004.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_005.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_006.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_007.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_008.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_009.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_010.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_011.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_012.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_013.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_014.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_015.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_016.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_017.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_018.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_019.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_020.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_021.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_022.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_023.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_024.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_025.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_026.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_027.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_028.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_029.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_030.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_031.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_032.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_033.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_034.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_035.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_036.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_037.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_038.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_039.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_040.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_041.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_042.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_043.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_044.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_045.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_046.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_047.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_048.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_049.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_050.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_051.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_052.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_053.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_054.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_055.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_056.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_057.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_058.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_059.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_060.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_061.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_062.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_063.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_064.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_065.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_066.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_067.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_068.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_069.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_070.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_071.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_072.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_073.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_074.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_075.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_076.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_077.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_078.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_079.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_088.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_089.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_090.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_094_1.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_094_2.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_096.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_098.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_099.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_100.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_101.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_102.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_103.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_105.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_106.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_107.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_108.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_109.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_110.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_111.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_112.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_creation_HA/YW_CETFSS_SHSG_115.py

