python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_001.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_002.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_003.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_004.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_005.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_006.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_007.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_008.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_009.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_010.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_011.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_012.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_013.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_014.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_015.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_016.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_017.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_018.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_019.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_020.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_021.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_022.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_023.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_024.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_025.py
python /home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_026.py
python /home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_027.py
python /home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_028.py
#python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_029.py
##python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_035.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_041.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_042.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_043.py
##python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_045.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_047_2.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_047_3.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_049.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_050.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_051.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_052.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_053.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_054.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_055.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_056.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_057.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_058.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_059.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_060.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_061.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_062.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_063.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_064.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_065.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_066.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_067.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_068.py
python	/home/yhl2/workspace/xtp_test/ETF/Redemption_SA/YW_ETFSS_SZSH_069.py
