python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_001.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_002.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_003.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_004.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_005.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_006.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_007.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_008.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_009.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_010.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_011.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_012.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_013.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_014.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_015.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_016.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_017.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_018.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_019.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_020.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_021.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_022.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_023.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_024.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_025.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_026.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_027.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_028.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_029.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_030.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_031.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_032.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_033.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_034.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_035.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_036.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_037.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_038.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_039.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_040.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_041.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_042.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_043.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_044.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_045.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_046.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_047.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_057.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_058.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_059.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_063_1.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_063_2.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_065.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_066.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_067.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_068.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_069.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_070.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_071.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_072.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_073.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_074.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_075.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_076.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_077.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_078.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_079.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_080.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_081.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_082.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_083.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_084.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_085.py
python /home/yhl2/workspace/xtp_test/crossmarketetf/crossmarket_redemption_HA/YW_CETFSS_SHSH_086.py

