python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_001.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_002.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_003.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_004.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_005.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_006.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_007.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_008.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_009.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_010.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_011.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_012.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_013.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_014.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_015.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_016.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_017.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_018.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_019.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_020.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_021.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_022.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_023.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_024.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_025.py
python  /home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_027.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_026.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_028.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_029.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_030.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_031.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_032.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_033.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_034.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_035.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_036.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_037.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_038.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_039.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_040.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_041.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_042.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_043.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_044.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_045.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_046.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_047.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_048.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_049.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_050.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_051.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_052.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_054.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_055.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_056.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_057.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_058.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_059.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_060.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_061.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_062.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_063.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_064.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_065_2.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_065_3.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_067.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_068.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_069.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_070.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_071.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_072.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_073.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_074.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_075.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_076.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_077.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_078.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_079.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_080.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_081.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_082.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_083.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_084.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_085.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_086.py
