python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_048.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_049.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_050.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_051.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_052.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_054.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_055.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_056.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_057.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_058.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_059.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_060.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_061.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_062.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_063.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_064.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_065_2.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_065_3.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_066.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_067.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_068.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_069.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_070.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_071.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_072.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_073.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_074.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_075.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_076.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_077.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_078.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_079.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_080.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_081.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_082.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_083.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_084.py
#python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_085.py
python	/home/yhl2/workspace/xtp_test/ETF/Creation_HA/YW_ETFSS_SHSG_086.py
